[colors.primary]
background = "0x1e1e1e"
foreground = "0xffffff"

[font]
size = 15.0

[font.bold]
family = "Terminus"
style = "Bold"

[font.italic]
family = "Terminus"
style = "Italic"

[font.normal]
family = "knxt"
style = "Regular"

[window]
opacity = 0.8
