#!/bin/bash
[bat]
command=test -e /usr/bin/acpi && acpi | awk '{print $4}' | sed 's/,//g'
interval=1
color=#FFFFFF

[current_window]
command=test -e /usr/bin/acpi || xdotool getwindowfocus getwindowname
interval=1
color=#FFFFFF
align=center
min_width=1222

[cpu]
command=top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{printf "%6.2f\n", 100 - $1}'

interval=1
color=#FFFFFF                

[ram]
command=free | awk '/Mem/{printf("%.2f/%.2f\n", $3/1024000, $2/1024000)}'
interval=1
color=#FFFFFF

[disk]
command=df -h . | tail -n1 | awk '{print $3"/"$4}' | tr -d 'G'
interval=1
color=#FFFFFF

[date]
command=date +"%D %T"
interval=1
color=#FFFFFF




